import Logo from "./logo.svg"
import HeroBg from "./hero-bg.png"
import HeroContent from "./hero-content-img.svg"
import Card1 from "./card1.png"
import Card2 from "./card2.png"
import Card3 from "./card3.png"
import Card4 from "./card4.png"
import sCase1 from "./sCase1.png"
import sCase2 from "./sCase2.png"
import supportive1 from "./Supportive1.png"
import supportive2 from "./Supportive2.png"
import supportive3 from "./Supportive3.png"
import supportive4 from "./Supportive4.png"
import utility1 from "./utility1.png"
import utility2 from "./utility2.png"
import utility3 from "./utility3.png"
import utility4 from "./utility4.png"
import utility5 from "./utility5.png"
import Ready1 from "./imgready.png"

export {Logo, HeroBg, HeroContent, Card1, Card2, Card3, Card4, sCase1, sCase2, supportive1, supportive2, supportive3, supportive4, utility1, utility2, utility3, utility4, utility5, Ready1 }